### ISSUE TITLE
mvn install launcher build failure

### ISSUE THREAD

**Issue by quangmng** [Birch-san/arm-editor-launcher#3]
Something that has to do with resolving dependencies/artifacts (running on M1 Pro MacBook Pro 16")

<img width="2056" alt="image" src="https://user-images.githubusercontent.com/57740309/168424156-f3d19cda-9441-4254-b822-a61b7780257a.png">

Install log:
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/57740309/168424197-b50dc55a-8274-4190-b459-f7fec8b2cc22.png">

**Comment by Birch-san** [comment]
did you run `install-jogl.sh` successfully before doing this?

was the file `~/.m2/repository/org/jogamp/jogl/jogl-all/v2.4.0-rc4/jogl-all-v2.4.0-rc4.jar` (and its siblings, from this screenshot) successfully installed to your .m2 local registry?

<img width="2032" alt="image" src="https://user-images.githubusercontent.com/6141784/168430173-cb276fdc-b4cb-4abd-a528-5ecccf1c746d.png">

**Comment by quangmng** [comment]
Thank you for the rep, I think the 1st time I ran the install-jogl.sh command from your readme file the file path has "~" caused path defined incorrectly which I removed it. 
<img width="590" alt="image" src="https://user-images.githubusercontent.com/57740309/168438114-d40b5e55-c87a-45f0-9021-3f20825e664f.png">
![image](https://user-images.githubusercontent.com/57740309/168438309-c7203678-c918-458f-a252-198138908eb8.png)
Ran 2nd time, it compiled properly now.
<img width="2044" alt="complete jogl" src="https://user-images.githubusercontent.com/57740309/168436456-23f3e68f-b0fc-4f15-a929-43aa3f5342ef.png">
Hence,
<img width="1213" alt="compile success" src="https://user-images.githubusercontent.com/57740309/168437451-773445b6-b004-480c-8dbd-04ad13db514c.png">
So, what do I do next?

**Comment by Birch-san** [comment]
you've installed jogl artifacts to your maven registry, so the IntelliJ error from your screenshot should be fixed; you should try the IntelliJ step again (i.e. Option 1 from the README):  
https://github.com/Birch-san/arm-editor-launcher#option-1-install--run-with-intellij

**Comment by quangmng** [comment]
Yeah I got it running now, but stuck at this screen for a while now... 
<img width="2056" alt="image" src="https://user-images.githubusercontent.com/57740309/168450404-ca2340a6-ecac-4522-81b2-278ccf5d2587.png">
Even when running without the arm-launcher
<img width="2055" alt="image" src="https://user-images.githubusercontent.com/57740309/168450439-c00285c5-5953-4e6b-8e3c-0a183c4f7efb.png">
I think maybe this is Live2D issue though, not from your launcher so yeah
<img width="733" alt="image" src="https://user-images.githubusercontent.com/57740309/168450460-41ccb8c7-5e28-4940-8dab-bd285c86cad9.png">
(Live2D community site - https://community.live2d.com)

**Comment by Birch-san** [comment]
okay yeah, if it's happening with the official launcher too then seems like you have a different problem. 

Unofficial Launcher is working for me with latest Live2D Cubism Editor 4.1.05 on M1 macOS:  
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/6141784/168450589-bd099331-8300-4195-91a8-0dac700865b6.png">

Official Launcher is also working for me:  
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/6141784/168450687-76852bfa-f74a-41ac-8314-25f30686844c.png">

Both are responsive:  
<img width="852" alt="image" src="https://user-images.githubusercontent.com/6141784/168450777-ed0d44bc-0992-4939-b595-2696ac861e3a.png">

so yeah, I think you need to first figure out why your _official_ launcher is busted. it definitely works (slowly) on M1 macOS.  
fun fact: if you get the official launcher working, you can make it run much faster by deleting `'/Applications/Live2D Cubism 4.1/res/libjpen-2-3.jnilib'` (that native library for pen tablets introduces crazy amounts of UI latency).

regarding the warning on their website:

> "[NOTICE]" About the support for Mac models  
> Cubism Editor is not supported with Apple M1 processors.

it's true that they don't support it officially. but as you can see from my screenshots above, it _can_ work. not sure what's different about your setup. 😕

**Comment by quangmng** [comment]
Yeah I tried to reinstall L2D by removing the /Applications/Live2D Cubism 4.1 folder and downloaded the latest installer from the official site. Tried restarting my mac as well and still not responding...
Interestingly that you bought up the pen tablet latency issue... Maybe it has something to do with me installing the Wacom tablet driver? 

(Edit: Seemed like I have background apps I use (karabiner-elements - key binder, whatpulse, bettersnaptool). One of those might prevent L2D from loading)

**Comment by quangmng** [comment]
Update: it works **really well**, thanks again for walking me thru the installation!
<img width="1007" alt="image" src="https://user-images.githubusercontent.com/57740309/168452125-8ebc38c9-1fc3-4472-9102-e89700f607b3.png">
x2 faster than Intel build :))
<img width="2056" alt="image" src="https://user-images.githubusercontent.com/57740309/168453785-8effa2b1-39e5-4797-8c13-93eebcb35e5c.png">

**Comment by SuCicada** [comment]
> 



> (Edit: Seemed like I have background apps I use (karabiner-elements - key binder, whatpulse, bettersnaptool). One of those might prevent L2D from loading)

very thanks for your advice, I've been stuck for many months. It's fine after I close the [Contexts](https://contexts.co/) software, but I don't know why this happens
